//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=HOMER\\SQL2008;Initial Catalog=MIPSED7_develop;Persist Security Info=T" +
            "rue;User ID=mipsed7;Password=mip7VUG937956")]
        public string MIPSED7_developConnectionString {
            get {
                return ((string)(this["MIPSED7_developConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\VUGER2008;Initial Catalog=MIPSED7_develop;Integrated Security=True")]
        public string MIPSED7_developConnectionString1 {
            get {
                return ((string)(this["MIPSED7_developConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RAZVOJ-PC-1\\VUGER2008;Initial Catalog=MIPSED7_GOP1;Persist Security I" +
            "nfo=True;User ID=mipsed7;Password=mip7VUG937956")]
        public string MIPSED7_GOP1ConnectionString {
            get {
                return ((string)(this["MIPSED7_GOP1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RAZVOJ-PC-1\\VUGER2008;Initial Catalog=MIPSED7_JOPPD;Persist Security " +
            "Info=True;User ID=mipsed7;Password=mip7VUG937956")]
        public string MIPSED7_JOPPDConnectionString {
            get {
                return ((string)(this["MIPSED7_JOPPDConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=ZAgi2302;Initial Catalog=MIPSED7;User ID=mipsed7;Password=mip7VUG9379" +
            "56")]
        public string MIPSED7ConnectionString {
            get {
                return ((string)(this["MIPSED7ConnectionString"]));
            }
        }
    }
}
