//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mipsed.application.framework {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FrameworkResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FrameworkResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mipsed.application.framework.FrameworkResources", typeof(FrameworkResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update porez set moporez = &apos;68&apos;
        ///go
        ///update doprinos set modoprinos = &apos;68&apos;
        ///go
        ///update krizniporez set mokrizni = &apos;68&apos;
        ///go
        ///update DDKATEGORIJALevel1 set ddmoporez = &apos;68&apos;
        ///go
        ///if not exists (select  top 1 ddidizdatak from ddizdatak where ddidizdatak = 1)
        ///begin
        ///INSERT INTO [dbo].[DDIZDATAK] ([DDIDIZDATAK], [DDNAZIVIZDATKA], [DDPOSTOTAKIZDATKA]) VALUES (1, N&apos;priznati troškovi 30%&apos;, 30.0000)
        ///end
        ///if not exists (select  top 1 ddidizdatak from ddizdatak where ddidizdatak = 2)
        ///begin
        ///INSERT INTO [dbo].[DDIZDA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dd_module {
            get {
                return ResourceManager.GetString("dd_module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ErrorText {
            get {
                return ResourceManager.GetString("ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešni format baze.
        /// </summary>
        public static string IncorrectDatabaseFormatException {
            get {
                return ResourceManager.GetString("IncorrectDatabaseFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string invalidUserPassword {
            get {
                return ResourceManager.GetString("invalidUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo aktivirajte aplikaciju u administrativnim alatima..
        /// </summary>
        public static string NotActivated {
            get {
                return ResourceManager.GetString("NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE POREZ SET STOPAPOREZa = 12,NAZIVPOREZ = &apos;Porez 12 %&apos;,porezmjesecno = 3600 WHERE IDPOREZ = 1
        ///GO
        ///UPDATE POREZ SET STOPAPOREZa = 25,NAZIVPOREZ = &apos;Porez 25 %&apos;,porezmjesecno = 7200 WHERE IDPOREZ = 2
        ///GO
        ///UPDATE POREZ SET STOPAPOREZa = 40,NAZIVPOREZ = &apos;Porez 40 %&apos;,porezmjesecno = 99999 WHERE IDPOREZ = 3
        ///GO
        ///update grupeolaksica set maximalniiznosgrupe = 0 where maximalniiznosgrupe  &gt; 500
        ///go
        ///delete from skupporezaidoprinosa1 where idporez = 4
        ///go
        ///
        ///if not exists (select  top 1 idporez from porez where [rest of string was truncated]&quot;;.
        /// </summary>
        public static string novizakon {
            get {
                return ResourceManager.GetString("novizakon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftMargin.
        /// </summary>
        public static string RegParamLeftMargin {
            get {
                return ResourceManager.GetString("RegParamLeftMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TopMargin.
        /// </summary>
        public static string RegParamTopMargin {
            get {
                return ResourceManager.GetString("RegParamTopMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT     dbo.KORISNIK.PROFILECATALOG, dbo.USERS.IDUSER, dbo.USERS.KORISNIKUSERIDKORISNIK, dbo.USERS.PWDUSER, 
        ///                      dbo.KORISNIK.KORISNIK1NAZIV, dbo.KORISNIK.KORISNIK1ADRESA, dbo.KORISNIK.KORISNIK1MJESTO, dbo.KORISNIK.MBKORISNIK, 
        ///                      dbo.KORISNIK.MBKORISNIKJEDINICA, dbo.KORISNIK.JMBGKORISNIK, dbo.KORISNIK.KONTAKTOSOBA, dbo.KORISNIK.KONTAKTTELEFON, 
        ///                      dbo.KORISNIK.KONTAKTFAX, dbo.KORISNIK.EMAIL, dbo.KORISNIK.NADLEZNAPU, dbo.KORISNIK.STAZUKOEFICIJENT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SelectUserKorisnik {
            get {
                return ResourceManager.GetString("SelectUserKorisnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string SubmenuPicture {
            get {
                return ResourceManager.GetString("SubmenuPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIPSED.7 - Računovodstvo proračuna.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [dbo].[POSTANSKIBROJEVI](
        ///	[POSTANSKIBROJ] [nvarchar](5) COLLATE Croatian_CI_AS NOT NULL,
        ///	[NAZIVPOSTE] [nvarchar](50) COLLATE Croatian_CI_AS NOT NULL
        ///) ON [PRIMARY]
        ///GO
        ///
        ///if not exists (select  top 1 POSTANSKIBROJ from POSTANSKIBROJEVI where POSTANSKIBROJ = 0)
        ///begin
        ///INSERT INTO [dbo].[POSTANSKIBROJEVI] ([POSTANSKIBROJ], [NAZIVPOSTE]) VALUES (0, N&apos;NEPOZNATA POŠTA&apos;)
        ///end
        ///GO
        ///
        ///if exists ( select * from INFORMATION_SCHEMA.COLUMNS
        ///where TABLE_NAME=&apos;UCENIK&apos; 
        ///and COLUMN_NAME=&apos;AKTIVANZARSM&apos;) [rest of string was truncated]&quot;;.
        /// </summary>
        public static string update {
            get {
                return ResourceManager.GetString("update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET ANSI_NULLS ON
        ///GO
        ///SET QUOTED_IDENTIFIER ON
        ///GO
        ///if exists (select * from dbo.sysobjects where id = object_id(N&apos;[dbo].[verzija]&apos;) and OBJECTPROPERTY(id, N&apos;IsUserTable&apos;) = 1)
        ///drop table [dbo].[verzija]
        ///GO
        ///CREATE TABLE [dbo].[VERZIJA](
        ///	[IDVERZIJA] [int] NOT NULL,
        ///	[VERZIJA] [nvarchar](20) NOT NULL,
        ///PRIMARY KEY CLUSTERED 
        ///(
        ///	[IDVERZIJA] ASC
        ///)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
        ///) ON [PRIMARY]
        ///go        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string verzija1 {
            get {
                return ResourceManager.GetString("verzija1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap vugericon {
            get {
                object obj = ResourceManager.GetObject("vugericon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogrešan unos korisničkog imena ili zaporke..
        /// </summary>
        public static string WrongUserPassword {
            get {
                return ResourceManager.GetString("WrongUserPassword", resourceCulture);
            }
        }
    }
}
