//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
///Represents a strongly typed in-memory cache of data.
///</summary>
[global::System.Serializable()]
[global::System.ComponentModel.DesignerCategoryAttribute("code")]
[global::System.ComponentModel.ToolboxItem(true)]
[global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
[global::System.Xml.Serialization.XmlRootAttribute("VIRMANIDataSet")]
[global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
public partial class VIRMANIDataSet : global::System.Data.DataSet {
    
    private VIRMANIDataTable tableVIRMANI;
    
    private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    public VIRMANIDataSet() {
        this.BeginInit();
        this.InitClass();
        global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
        base.Tables.CollectionChanged += schemaChangedHandler;
        base.Relations.CollectionChanged += schemaChangedHandler;
        this.EndInit();
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    protected VIRMANIDataSet(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
            base(info, context, false) {
        if ((this.IsBinarySerialized(info, context) == true)) {
            this.InitVars(false);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler1;
            this.Relations.CollectionChanged += schemaChangedHandler1;
            return;
        }
        string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
        if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
            global::System.Data.DataSet ds = new global::System.Data.DataSet();
            ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            if ((ds.Tables["VIRMANI"] != null)) {
                base.Tables.Add(new VIRMANIDataTable(ds.Tables["VIRMANI"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        else {
            this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
        }
        this.GetSerializationData(info, context);
        global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
        base.Tables.CollectionChanged += schemaChangedHandler;
        this.Relations.CollectionChanged += schemaChangedHandler;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    [global::System.ComponentModel.Browsable(false)]
    [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
    public VIRMANIDataTable VIRMANI {
        get {
            return this.tableVIRMANI;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    [global::System.ComponentModel.BrowsableAttribute(true)]
    [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
    public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
        get {
            return this._schemaSerializationMode;
        }
        set {
            this._schemaSerializationMode = value;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public new global::System.Data.DataTableCollection Tables {
        get {
            return base.Tables;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
    public new global::System.Data.DataRelationCollection Relations {
        get {
            return base.Relations;
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    protected override void InitializeDerivedDataSet() {
        this.BeginInit();
        this.InitClass();
        this.EndInit();
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    public override global::System.Data.DataSet Clone() {
        VIRMANIDataSet cln = ((VIRMANIDataSet)(base.Clone()));
        cln.InitVars();
        cln.SchemaSerializationMode = this.SchemaSerializationMode;
        return cln;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    protected override bool ShouldSerializeTables() {
        return false;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    protected override bool ShouldSerializeRelations() {
        return false;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
        if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
            this.Reset();
            global::System.Data.DataSet ds = new global::System.Data.DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["VIRMANI"] != null)) {
                base.Tables.Add(new VIRMANIDataTable(ds.Tables["VIRMANI"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        else {
            this.ReadXml(reader);
            this.InitVars();
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
        global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
        this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
        stream.Position = 0;
        return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    internal void InitVars() {
        this.InitVars(true);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    internal void InitVars(bool initTable) {
        this.tableVIRMANI = ((VIRMANIDataTable)(base.Tables["VIRMANI"]));
        if ((initTable == true)) {
            if ((this.tableVIRMANI != null)) {
                this.tableVIRMANI.InitVars();
            }
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    private void InitClass() {
        this.DataSetName = "VIRMANIDataSet";
        this.Prefix = "";
        this.Namespace = "http://www.tempuri.org/VIRMANI";
        this.Locale = new global::System.Globalization.CultureInfo("en-US");
        this.EnforceConstraints = true;
        this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        this.tableVIRMANI = new VIRMANIDataTable();
        base.Tables.Add(this.tableVIRMANI);
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    private bool ShouldSerializeVIRMANI() {
        return false;
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
        if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
            this.InitVars();
        }
    }
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
        VIRMANIDataSet ds = new VIRMANIDataSet();
        global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
        global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
        global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
        any.Namespace = ds.Namespace;
        sequence.Items.Add(any);
        type.Particle = sequence;
        global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
        if (xs.Contains(dsSchema.TargetNamespace)) {
            global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
            global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
            try {
                global::System.Xml.Schema.XmlSchema schema = null;
                dsSchema.Write(s1);
                for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                    schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                    s2.SetLength(0);
                    schema.Write(s2);
                    if ((s1.Length == s2.Length)) {
                        s1.Position = 0;
                        s2.Position = 0;
                        for (; ((s1.Position != s1.Length) 
                                    && (s1.ReadByte() == s2.ReadByte())); ) {
                            ;
                        }
                        if ((s1.Position == s1.Length)) {
                            return type;
                        }
                    }
                }
            }
            finally {
                if ((s1 != null)) {
                    s1.Close();
                }
                if ((s2 != null)) {
                    s2.Close();
                }
            }
        }
        xs.Add(dsSchema);
        return type;
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    public delegate void VIRMANIRowChangeEventHandler(object sender, VIRMANIRowChangeEvent e);
    
    /// <summary>
    ///Represents the strongly named DataTable class.
    ///</summary>
    [global::System.Serializable()]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
    public partial class VIRMANIDataTable : global::System.Data.TypedTableBase<VIRMANIRow> {
        
        private global::System.Data.DataColumn columnIDVIRMAN;
        
        private global::System.Data.DataColumn columnSIFRAOBRACUNAVIRMAN;
        
        private global::System.Data.DataColumn columnPLA1;
        
        private global::System.Data.DataColumn columnPLA2;
        
        private global::System.Data.DataColumn columnPLA3;
        
        private global::System.Data.DataColumn columnBROJRACUNAPLA;
        
        private global::System.Data.DataColumn columnMODELZADUZENJA;
        
        private global::System.Data.DataColumn columnPOZIVZADUZENJA;
        
        private global::System.Data.DataColumn columnPRI1;
        
        private global::System.Data.DataColumn columnPRI2;
        
        private global::System.Data.DataColumn columnPRI3;
        
        private global::System.Data.DataColumn columnBROJRACUNAPRI;
        
        private global::System.Data.DataColumn columnMODELODOBRENJA;
        
        private global::System.Data.DataColumn columnPOZIVODOBRENJA;
        
        private global::System.Data.DataColumn columnSIFRAOPISAPLACANJAVIRMAN;
        
        private global::System.Data.DataColumn columnOPISPLACANJAVIRMAN;
        
        private global::System.Data.DataColumn columnDATUMVALUTE;
        
        private global::System.Data.DataColumn columnDATUMPODNOSENJA;
        
        private global::System.Data.DataColumn columnIZVORDOKUMENTA;
        
        private global::System.Data.DataColumn columnOZNACEN;
        
        private global::System.Data.DataColumn columnIZNOS;
        
        private global::System.Data.DataColumn columnNAMJENA;
        
        private global::System.Data.DataColumn columnHUB3_SIFRANAMJENE;
        
        private global::System.Data.DataColumn columnHUB3_HITNO;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public VIRMANIDataTable() {
            this.TableName = "VIRMANI";
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal VIRMANIDataTable(global::System.Data.DataTable table) {
            this.TableName = table.TableName;
            if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                this.CaseSensitive = table.CaseSensitive;
            }
            if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                this.Locale = table.Locale;
            }
            if ((table.Namespace != table.DataSet.Namespace)) {
                this.Namespace = table.Namespace;
            }
            this.Prefix = table.Prefix;
            this.MinimumCapacity = table.MinimumCapacity;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected VIRMANIDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context) {
            this.InitVars();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn IDVIRMANColumn {
            get {
                return this.columnIDVIRMAN;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn SIFRAOBRACUNAVIRMANColumn {
            get {
                return this.columnSIFRAOBRACUNAVIRMAN;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn PLA1Column {
            get {
                return this.columnPLA1;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn PLA2Column {
            get {
                return this.columnPLA2;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn PLA3Column {
            get {
                return this.columnPLA3;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn BROJRACUNAPLAColumn {
            get {
                return this.columnBROJRACUNAPLA;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn MODELZADUZENJAColumn {
            get {
                return this.columnMODELZADUZENJA;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn POZIVZADUZENJAColumn {
            get {
                return this.columnPOZIVZADUZENJA;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn PRI1Column {
            get {
                return this.columnPRI1;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn PRI2Column {
            get {
                return this.columnPRI2;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn PRI3Column {
            get {
                return this.columnPRI3;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn BROJRACUNAPRIColumn {
            get {
                return this.columnBROJRACUNAPRI;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn MODELODOBRENJAColumn {
            get {
                return this.columnMODELODOBRENJA;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn POZIVODOBRENJAColumn {
            get {
                return this.columnPOZIVODOBRENJA;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn SIFRAOPISAPLACANJAVIRMANColumn {
            get {
                return this.columnSIFRAOPISAPLACANJAVIRMAN;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn OPISPLACANJAVIRMANColumn {
            get {
                return this.columnOPISPLACANJAVIRMAN;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn DATUMVALUTEColumn {
            get {
                return this.columnDATUMVALUTE;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn DATUMPODNOSENJAColumn {
            get {
                return this.columnDATUMPODNOSENJA;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn IZVORDOKUMENTAColumn {
            get {
                return this.columnIZVORDOKUMENTA;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn OZNACENColumn {
            get {
                return this.columnOZNACEN;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn IZNOSColumn {
            get {
                return this.columnIZNOS;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn NAMJENAColumn {
            get {
                return this.columnNAMJENA;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn HUB3_SIFRANAMJENEColumn {
            get {
                return this.columnHUB3_SIFRANAMJENE;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataColumn HUB3_HITNOColumn {
            get {
                return this.columnHUB3_HITNO;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        [global::System.ComponentModel.Browsable(false)]
        public int Count {
            get {
                return this.Rows.Count;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public VIRMANIRow this[int index] {
            get {
                return ((VIRMANIRow)(this.Rows[index]));
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public event VIRMANIRowChangeEventHandler VIRMANIRowChanging;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public event VIRMANIRowChangeEventHandler VIRMANIRowChanged;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public event VIRMANIRowChangeEventHandler VIRMANIRowDeleting;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public event VIRMANIRowChangeEventHandler VIRMANIRowDeleted;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public void AddVIRMANIRow(VIRMANIRow row) {
            this.Rows.Add(row);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public VIRMANIRow AddVIRMANIRow(
                    int IDVIRMAN, 
                    string SIFRAOBRACUNAVIRMAN, 
                    string PLA1, 
                    string PLA2, 
                    string PLA3, 
                    string BROJRACUNAPLA, 
                    string MODELZADUZENJA, 
                    string POZIVZADUZENJA, 
                    string PRI1, 
                    string PRI2, 
                    string PRI3, 
                    string BROJRACUNAPRI, 
                    string MODELODOBRENJA, 
                    string POZIVODOBRENJA, 
                    string SIFRAOPISAPLACANJAVIRMAN, 
                    string OPISPLACANJAVIRMAN, 
                    System.DateTime DATUMVALUTE, 
                    System.DateTime DATUMPODNOSENJA, 
                    string IZVORDOKUMENTA, 
                    bool OZNACEN, 
                    decimal IZNOS, 
                    string NAMJENA, 
                    string HUB3_SIFRANAMJENE, 
                    bool HUB3_HITNO) {
            VIRMANIRow rowVIRMANIRow = ((VIRMANIRow)(this.NewRow()));
            object[] columnValuesArray = new object[] {
                    IDVIRMAN,
                    SIFRAOBRACUNAVIRMAN,
                    PLA1,
                    PLA2,
                    PLA3,
                    BROJRACUNAPLA,
                    MODELZADUZENJA,
                    POZIVZADUZENJA,
                    PRI1,
                    PRI2,
                    PRI3,
                    BROJRACUNAPRI,
                    MODELODOBRENJA,
                    POZIVODOBRENJA,
                    SIFRAOPISAPLACANJAVIRMAN,
                    OPISPLACANJAVIRMAN,
                    DATUMVALUTE,
                    DATUMPODNOSENJA,
                    IZVORDOKUMENTA,
                    OZNACEN,
                    IZNOS,
                    NAMJENA,
                    HUB3_SIFRANAMJENE,
                    HUB3_HITNO};
            rowVIRMANIRow.ItemArray = columnValuesArray;
            this.Rows.Add(rowVIRMANIRow);
            return rowVIRMANIRow;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public VIRMANIRow FindByIDVIRMAN(int IDVIRMAN) {
            return ((VIRMANIRow)(this.Rows.Find(new object[] {
                        IDVIRMAN})));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public override global::System.Data.DataTable Clone() {
            VIRMANIDataTable cln = ((VIRMANIDataTable)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Data.DataTable CreateInstance() {
            return new VIRMANIDataTable();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal void InitVars() {
            this.columnIDVIRMAN = base.Columns["IDVIRMAN"];
            this.columnSIFRAOBRACUNAVIRMAN = base.Columns["SIFRAOBRACUNAVIRMAN"];
            this.columnPLA1 = base.Columns["PLA1"];
            this.columnPLA2 = base.Columns["PLA2"];
            this.columnPLA3 = base.Columns["PLA3"];
            this.columnBROJRACUNAPLA = base.Columns["BROJRACUNAPLA"];
            this.columnMODELZADUZENJA = base.Columns["MODELZADUZENJA"];
            this.columnPOZIVZADUZENJA = base.Columns["POZIVZADUZENJA"];
            this.columnPRI1 = base.Columns["PRI1"];
            this.columnPRI2 = base.Columns["PRI2"];
            this.columnPRI3 = base.Columns["PRI3"];
            this.columnBROJRACUNAPRI = base.Columns["BROJRACUNAPRI"];
            this.columnMODELODOBRENJA = base.Columns["MODELODOBRENJA"];
            this.columnPOZIVODOBRENJA = base.Columns["POZIVODOBRENJA"];
            this.columnSIFRAOPISAPLACANJAVIRMAN = base.Columns["SIFRAOPISAPLACANJAVIRMAN"];
            this.columnOPISPLACANJAVIRMAN = base.Columns["OPISPLACANJAVIRMAN"];
            this.columnDATUMVALUTE = base.Columns["DATUMVALUTE"];
            this.columnDATUMPODNOSENJA = base.Columns["DATUMPODNOSENJA"];
            this.columnIZVORDOKUMENTA = base.Columns["IZVORDOKUMENTA"];
            this.columnOZNACEN = base.Columns["OZNACEN"];
            this.columnIZNOS = base.Columns["IZNOS"];
            this.columnNAMJENA = base.Columns["NAMJENA"];
            this.columnHUB3_SIFRANAMJENE = base.Columns["HUB3_SIFRANAMJENE"];
            this.columnHUB3_HITNO = base.Columns["HUB3_HITNO"];
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        private void InitClass() {
            this.columnIDVIRMAN = new global::System.Data.DataColumn("IDVIRMAN", typeof(int), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnIDVIRMAN);
            this.columnSIFRAOBRACUNAVIRMAN = new global::System.Data.DataColumn("SIFRAOBRACUNAVIRMAN", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnSIFRAOBRACUNAVIRMAN);
            this.columnPLA1 = new global::System.Data.DataColumn("PLA1", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPLA1);
            this.columnPLA2 = new global::System.Data.DataColumn("PLA2", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPLA2);
            this.columnPLA3 = new global::System.Data.DataColumn("PLA3", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPLA3);
            this.columnBROJRACUNAPLA = new global::System.Data.DataColumn("BROJRACUNAPLA", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnBROJRACUNAPLA);
            this.columnMODELZADUZENJA = new global::System.Data.DataColumn("MODELZADUZENJA", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnMODELZADUZENJA);
            this.columnPOZIVZADUZENJA = new global::System.Data.DataColumn("POZIVZADUZENJA", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPOZIVZADUZENJA);
            this.columnPRI1 = new global::System.Data.DataColumn("PRI1", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPRI1);
            this.columnPRI2 = new global::System.Data.DataColumn("PRI2", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPRI2);
            this.columnPRI3 = new global::System.Data.DataColumn("PRI3", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPRI3);
            this.columnBROJRACUNAPRI = new global::System.Data.DataColumn("BROJRACUNAPRI", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnBROJRACUNAPRI);
            this.columnMODELODOBRENJA = new global::System.Data.DataColumn("MODELODOBRENJA", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnMODELODOBRENJA);
            this.columnPOZIVODOBRENJA = new global::System.Data.DataColumn("POZIVODOBRENJA", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnPOZIVODOBRENJA);
            this.columnSIFRAOPISAPLACANJAVIRMAN = new global::System.Data.DataColumn("SIFRAOPISAPLACANJAVIRMAN", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnSIFRAOPISAPLACANJAVIRMAN);
            this.columnOPISPLACANJAVIRMAN = new global::System.Data.DataColumn("OPISPLACANJAVIRMAN", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnOPISPLACANJAVIRMAN);
            this.columnDATUMVALUTE = new global::System.Data.DataColumn("DATUMVALUTE", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnDATUMVALUTE);
            this.columnDATUMPODNOSENJA = new global::System.Data.DataColumn("DATUMPODNOSENJA", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnDATUMPODNOSENJA);
            this.columnIZVORDOKUMENTA = new global::System.Data.DataColumn("IZVORDOKUMENTA", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnIZVORDOKUMENTA);
            this.columnOZNACEN = new global::System.Data.DataColumn("OZNACEN", typeof(bool), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnOZNACEN);
            this.columnIZNOS = new global::System.Data.DataColumn("IZNOS", typeof(decimal), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnIZNOS);
            this.columnNAMJENA = new global::System.Data.DataColumn("NAMJENA", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnNAMJENA);
            this.columnHUB3_SIFRANAMJENE = new global::System.Data.DataColumn("HUB3_SIFRANAMJENE", typeof(string), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnHUB3_SIFRANAMJENE);
            this.columnHUB3_HITNO = new global::System.Data.DataColumn("HUB3_HITNO", typeof(bool), null, global::System.Data.MappingType.Element);
            base.Columns.Add(this.columnHUB3_HITNO);
            this.Constraints.Add(new global::System.Data.UniqueConstraint("VIRMANIConstraint1", new global::System.Data.DataColumn[] {
                            this.columnIDVIRMAN}, true));
            this.columnIDVIRMAN.AllowDBNull = false;
            this.columnIDVIRMAN.Unique = true;
            this.columnIDVIRMAN.DefaultValue = ((int)(0));
            this.columnSIFRAOBRACUNAVIRMAN.AllowDBNull = false;
            this.columnSIFRAOBRACUNAVIRMAN.DefaultValue = ((string)(""));
            this.columnPLA1.AllowDBNull = false;
            this.columnPLA1.DefaultValue = ((string)(""));
            this.columnPLA2.AllowDBNull = false;
            this.columnPLA2.DefaultValue = ((string)(""));
            this.columnPLA3.AllowDBNull = false;
            this.columnPLA3.DefaultValue = ((string)(""));
            this.columnBROJRACUNAPLA.AllowDBNull = false;
            this.columnBROJRACUNAPLA.DefaultValue = ((string)(""));
            this.columnMODELZADUZENJA.AllowDBNull = false;
            this.columnMODELZADUZENJA.DefaultValue = ((string)(""));
            this.columnPOZIVZADUZENJA.AllowDBNull = false;
            this.columnPOZIVZADUZENJA.DefaultValue = ((string)(""));
            this.columnPRI1.AllowDBNull = false;
            this.columnPRI1.DefaultValue = ((string)(""));
            this.columnPRI2.AllowDBNull = false;
            this.columnPRI2.DefaultValue = ((string)(""));
            this.columnPRI3.AllowDBNull = false;
            this.columnPRI3.DefaultValue = ((string)(""));
            this.columnBROJRACUNAPRI.AllowDBNull = false;
            this.columnBROJRACUNAPRI.DefaultValue = ((string)(""));
            this.columnMODELODOBRENJA.AllowDBNull = false;
            this.columnMODELODOBRENJA.DefaultValue = ((string)(""));
            this.columnPOZIVODOBRENJA.AllowDBNull = false;
            this.columnPOZIVODOBRENJA.DefaultValue = ((string)(""));
            this.columnSIFRAOPISAPLACANJAVIRMAN.AllowDBNull = false;
            this.columnSIFRAOPISAPLACANJAVIRMAN.DefaultValue = ((string)(""));
            this.columnOPISPLACANJAVIRMAN.AllowDBNull = false;
            this.columnOPISPLACANJAVIRMAN.DefaultValue = ((string)(""));
            this.columnDATUMVALUTE.AllowDBNull = false;
            this.columnDATUMPODNOSENJA.AllowDBNull = false;
            this.columnIZVORDOKUMENTA.AllowDBNull = false;
            this.columnIZVORDOKUMENTA.DefaultValue = ((string)(""));
            this.columnOZNACEN.AllowDBNull = false;
            this.columnIZNOS.AllowDBNull = false;
            this.columnIZNOS.DefaultValue = ((decimal)(0m));
            this.columnNAMJENA.AllowDBNull = false;
            this.columnNAMJENA.DefaultValue = ((string)(""));
            this.Namespace = "";
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public VIRMANIRow NewVIRMANIRow() {
            return ((VIRMANIRow)(this.NewRow()));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
            return new VIRMANIRow(builder);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override global::System.Type GetRowType() {
            return typeof(VIRMANIRow);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowChanged(e);
            if ((this.VIRMANIRowChanged != null)) {
                this.VIRMANIRowChanged(this, new VIRMANIRowChangeEvent(((VIRMANIRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowChanging(e);
            if ((this.VIRMANIRowChanging != null)) {
                this.VIRMANIRowChanging(this, new VIRMANIRowChangeEvent(((VIRMANIRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowDeleted(e);
            if ((this.VIRMANIRowDeleted != null)) {
                this.VIRMANIRowDeleted(this, new VIRMANIRowChangeEvent(((VIRMANIRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
            base.OnRowDeleting(e);
            if ((this.VIRMANIRowDeleting != null)) {
                this.VIRMANIRowDeleting(this, new VIRMANIRowChangeEvent(((VIRMANIRow)(e.Row)), e.Action));
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public void RemoveVIRMANIRow(VIRMANIRow row) {
            this.Rows.Remove(row);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            VIRMANIDataSet ds = new VIRMANIDataSet();
            global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
            any1.Namespace = "http://www.w3.org/2001/XMLSchema";
            any1.MinOccurs = new decimal(0);
            any1.MaxOccurs = decimal.MaxValue;
            any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
            sequence.Items.Add(any1);
            global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
            any2.MinOccurs = new decimal(1);
            any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
            sequence.Items.Add(any2);
            global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
            attribute1.Name = "#pragma warning disable 1591 namespace";
            attribute1.FixedValue = ds.Namespace;
            type.Attributes.Add(attribute1);
            global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
            attribute2.Name = "tableTypeName";
            attribute2.FixedValue = "VIRMANIDataTable";
            type.Attributes.Add(attribute2);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
    }
    
    /// <summary>
    ///Represents strongly named DataRow class.
    ///</summary>
    public partial class VIRMANIRow : global::System.Data.DataRow {
        
        private VIRMANIDataTable tableVIRMANI;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        internal VIRMANIRow(global::System.Data.DataRowBuilder rb) : 
                base(rb) {
            this.tableVIRMANI = ((VIRMANIDataTable)(this.Table));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public int IDVIRMAN {
            get {
                return ((int)(this[this.tableVIRMANI.IDVIRMANColumn]));
            }
            set {
                this[this.tableVIRMANI.IDVIRMANColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string SIFRAOBRACUNAVIRMAN {
            get {
                return ((string)(this[this.tableVIRMANI.SIFRAOBRACUNAVIRMANColumn]));
            }
            set {
                this[this.tableVIRMANI.SIFRAOBRACUNAVIRMANColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string PLA1 {
            get {
                return ((string)(this[this.tableVIRMANI.PLA1Column]));
            }
            set {
                this[this.tableVIRMANI.PLA1Column] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string PLA2 {
            get {
                return ((string)(this[this.tableVIRMANI.PLA2Column]));
            }
            set {
                this[this.tableVIRMANI.PLA2Column] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string PLA3 {
            get {
                return ((string)(this[this.tableVIRMANI.PLA3Column]));
            }
            set {
                this[this.tableVIRMANI.PLA3Column] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string BROJRACUNAPLA {
            get {
                return ((string)(this[this.tableVIRMANI.BROJRACUNAPLAColumn]));
            }
            set {
                this[this.tableVIRMANI.BROJRACUNAPLAColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string MODELZADUZENJA {
            get {
                return ((string)(this[this.tableVIRMANI.MODELZADUZENJAColumn]));
            }
            set {
                this[this.tableVIRMANI.MODELZADUZENJAColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string POZIVZADUZENJA {
            get {
                return ((string)(this[this.tableVIRMANI.POZIVZADUZENJAColumn]));
            }
            set {
                this[this.tableVIRMANI.POZIVZADUZENJAColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string PRI1 {
            get {
                return ((string)(this[this.tableVIRMANI.PRI1Column]));
            }
            set {
                this[this.tableVIRMANI.PRI1Column] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string PRI2 {
            get {
                return ((string)(this[this.tableVIRMANI.PRI2Column]));
            }
            set {
                this[this.tableVIRMANI.PRI2Column] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string PRI3 {
            get {
                return ((string)(this[this.tableVIRMANI.PRI3Column]));
            }
            set {
                this[this.tableVIRMANI.PRI3Column] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string BROJRACUNAPRI {
            get {
                return ((string)(this[this.tableVIRMANI.BROJRACUNAPRIColumn]));
            }
            set {
                this[this.tableVIRMANI.BROJRACUNAPRIColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string MODELODOBRENJA {
            get {
                return ((string)(this[this.tableVIRMANI.MODELODOBRENJAColumn]));
            }
            set {
                this[this.tableVIRMANI.MODELODOBRENJAColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string POZIVODOBRENJA {
            get {
                return ((string)(this[this.tableVIRMANI.POZIVODOBRENJAColumn]));
            }
            set {
                this[this.tableVIRMANI.POZIVODOBRENJAColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string SIFRAOPISAPLACANJAVIRMAN {
            get {
                return ((string)(this[this.tableVIRMANI.SIFRAOPISAPLACANJAVIRMANColumn]));
            }
            set {
                this[this.tableVIRMANI.SIFRAOPISAPLACANJAVIRMANColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string OPISPLACANJAVIRMAN {
            get {
                return ((string)(this[this.tableVIRMANI.OPISPLACANJAVIRMANColumn]));
            }
            set {
                this[this.tableVIRMANI.OPISPLACANJAVIRMANColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public System.DateTime DATUMVALUTE {
            get {
                return ((global::System.DateTime)(this[this.tableVIRMANI.DATUMVALUTEColumn]));
            }
            set {
                this[this.tableVIRMANI.DATUMVALUTEColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public System.DateTime DATUMPODNOSENJA {
            get {
                return ((global::System.DateTime)(this[this.tableVIRMANI.DATUMPODNOSENJAColumn]));
            }
            set {
                this[this.tableVIRMANI.DATUMPODNOSENJAColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string IZVORDOKUMENTA {
            get {
                return ((string)(this[this.tableVIRMANI.IZVORDOKUMENTAColumn]));
            }
            set {
                this[this.tableVIRMANI.IZVORDOKUMENTAColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public bool OZNACEN {
            get {
                return ((bool)(this[this.tableVIRMANI.OZNACENColumn]));
            }
            set {
                this[this.tableVIRMANI.OZNACENColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public decimal IZNOS {
            get {
                return ((decimal)(this[this.tableVIRMANI.IZNOSColumn]));
            }
            set {
                this[this.tableVIRMANI.IZNOSColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string NAMJENA {
            get {
                return ((string)(this[this.tableVIRMANI.NAMJENAColumn]));
            }
            set {
                this[this.tableVIRMANI.NAMJENAColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public string HUB3_SIFRANAMJENE {
            get {
                try {
                    return ((string)(this[this.tableVIRMANI.HUB3_SIFRANAMJENEColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'HUB3_SIFRANAMJENE\' in table \'VIRMANI\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVIRMANI.HUB3_SIFRANAMJENEColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public bool HUB3_HITNO {
            get {
                try {
                    return ((bool)(this[this.tableVIRMANI.HUB3_HITNOColumn]));
                }
                catch (global::System.InvalidCastException e) {
                    throw new global::System.Data.StrongTypingException("The value for column \'HUB3_HITNO\' in table \'VIRMANI\' is DBNull.", e);
                }
            }
            set {
                this[this.tableVIRMANI.HUB3_HITNOColumn] = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public bool IsHUB3_SIFRANAMJENENull() {
            return this.IsNull(this.tableVIRMANI.HUB3_SIFRANAMJENEColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public void SetHUB3_SIFRANAMJENENull() {
            this[this.tableVIRMANI.HUB3_SIFRANAMJENEColumn] = global::System.Convert.DBNull;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public bool IsHUB3_HITNONull() {
            return this.IsNull(this.tableVIRMANI.HUB3_HITNOColumn);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public void SetHUB3_HITNONull() {
            this[this.tableVIRMANI.HUB3_HITNOColumn] = global::System.Convert.DBNull;
        }
    }
    
    /// <summary>
    ///Row event argument class
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
    public class VIRMANIRowChangeEvent : global::System.EventArgs {
        
        private VIRMANIRow eventRow;
        
        private global::System.Data.DataRowAction eventAction;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public VIRMANIRowChangeEvent(VIRMANIRow row, global::System.Data.DataRowAction action) {
            this.eventRow = row;
            this.eventAction = action;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public VIRMANIRow Row {
            get {
                return this.eventRow;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")]
        public global::System.Data.DataRowAction Action {
            get {
                return this.eventAction;
            }
        }
    }
}

#pragma warning restore 1591