Begin
Alter Table PARTNER ADD Lokacija int NOT NULL Default 0
End 
GO

/****** Object:  StoredProcedure [dbo].[sp_OPZPartneri]    Script Date: 1.8.2016. 10:30:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_OPZPartneri]
(
    @DatumOd As date,
	@DatumDo As date
) AS
BEGIN

SELECT Distinct firstTable.IDPARTNER AS IDPARTNER,
		dbo.PARTNER.PARTNEROIB,
		dbo.PARTNER.NAZIVPARTNER
		,
		(Case When PARTNER.Lokacija = 0 Then 1 
		When PARTNER.Lokacija = 1 Then 2
		When PARTNER.Lokacija = 2 Then 3 End) As Oznaka
FROM    dbo.GKSTAVKA AS firstTable
        INNER JOIN dbo.DOKUMENT ON firstTable.IDDOKUMENT = dbo.DOKUMENT.IDDOKUMENT
        INNER JOIN dbo.ORGJED ON firstTable.IDORGJED = dbo.ORGJED.IDORGJED
        INNER JOIN dbo.MJESTOTROSKA ON firstTable.IDMJESTOTROSKA = dbo.MJESTOTROSKA.IDMJESTOTROSKA
        INNER JOIN dbo.KONTO ON firstTable.IDKONTO = dbo.KONTO.IDKONTO
        INNER JOIN dbo.PARTNER ON firstTable.IDPARTNER = dbo.PARTNER.IDPARTNER
		Inner Join IRA On firstTable.BROJDOKUMENTA = IRA.IRABROJ And firstTable.GKGODIDGODINE = IRA.IRAGODIDGODINE And firstTable.IDDOKUMENT = IRA.IRADOKIDDOKUMENT
WHERE   (firstTable.GKDATUMVALUTE <= @DatumOd  And firstTable.gkdatumvalute < @DatumDo )
        AND ( KONTO.IDAKTIVNOST > 1)
		And DATEDIFF(DAY, firstTable.GKDATUMVALUTE, @DatumDo ) > 0 
		And PARTNER.Ucenik = 0
		And (Select ISNULL(SUM(ZATVARANJAIZNOS), 0) From ZATVARANJA
		Inner Join GKSTAVKA On ZATVARANJA.GK1IDGKSTAVKA = GKSTAVKA.IDGKSTAVKA
		Where GKSTAVKA.DATUMDOKUMENTA <= @DatumDo And GK2IDGKSTAVKA = firstTable.IDGKSTAVKA ) <> IRA.IRAUKUPNO 

ORDER BY firstTable.IDPARTNER

END
GO


/****** Object:  StoredProcedure [dbo].[sp_OPZStavke]    Script Date: 1.8.2016. 10:30:06 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_OPZStavke]

(
	@DatumOD as date,
	@DatumDo as date
)
AS

SELECT	firstTbl.IDGKSTAVKA As ID,
		firstTbl.IDPARTNER AS IDPARTNER,
		firstTbl.BROJDOKUMENTA As BrojIzdanogRacuna,
		firstTbl.DATUMDOKUMENTA As DatumIzdanogRacuna,
		firstTbl.GKDATUMVALUTE AS ValutaPlacanja,
		DATEDIFF(DAY, firstTbl.GKDATUMVALUTE, @DatumDo) As BrojDanaKasnjenja,
		(IRA.IRAUKUPNO - (IRA.PDV05 + IRA.PDV10 + IRA.PDV22 + IRA.PDV23 + IRA.PDV25)) As IznosRacuna,
		(IRA.PDV05 + IRA.PDV10 + IRA.PDV22 + IRA.PDV23 + IRA.PDV25) As IznosPDVa,
		IRA.IRAUKUPNO As UkupanIznosSaPDVom,
		(Select ISNULL(SUM(ZATVARANJAIZNOS), 0) From ZATVARANJA
		Inner Join GKSTAVKA On ZATVARANJA.GK1IDGKSTAVKA = GKSTAVKA.IDGKSTAVKA
		Where GKSTAVKA.DATUMDOKUMENTA <= @datumDo And GK2IDGKSTAVKA = firstTbl.IDGKSTAVKA) As PlaceniIznosRacuna,
		(IRA.IRAUKUPNO - (Select ISNULL(SUM(ZATVARANJAIZNOS), 0) From ZATVARANJA
		Inner Join GKSTAVKA On ZATVARANJA.GK1IDGKSTAVKA = GKSTAVKA.IDGKSTAVKA
		Where GKSTAVKA.DATUMDOKUMENTA <= @datumDo And GK2IDGKSTAVKA = firstTbl.IDGKSTAVKA)) As NeplaceniDioRacuna


FROM    dbo.GKSTAVKA As firstTbl
        INNER JOIN dbo.DOKUMENT ON firstTbl.IDDOKUMENT = dbo.DOKUMENT.IDDOKUMENT
        INNER JOIN dbo.ORGJED ON firstTbl.IDORGJED = dbo.ORGJED.IDORGJED
        INNER JOIN dbo.MJESTOTROSKA ON firstTbl.IDMJESTOTROSKA = dbo.MJESTOTROSKA.IDMJESTOTROSKA
        INNER JOIN dbo.KONTO ON firstTbl.IDKONTO = dbo.KONTO.IDKONTO
        INNER JOIN dbo.PARTNER ON firstTbl.IDPARTNER = dbo.PARTNER.IDPARTNER
		Inner Join IRA On firstTbl.BROJDOKUMENTA = IRA.IRABROJ And firstTbl.GKGODIDGODINE = IRA.IRAGODIDGODINE And firstTbl.IDDOKUMENT = IRA.IRADOKIDDOKUMENT
WHERE   
	    (KONTO.IDAKTIVNOST > 1)
		And DATEDIFF(DAY, firstTbl.GKDATUMVALUTE, @DatumDo) > 0 
		And PARTNER.Ucenik = 0
		And (Select ISNULL(SUM(ZATVARANJAIZNOS), 0) From ZATVARANJA
		Inner Join GKSTAVKA On ZATVARANJA.GK1IDGKSTAVKA = GKSTAVKA.IDGKSTAVKA
		Where GKSTAVKA.DATUMDOKUMENTA <= @datumDo And GK2IDGKSTAVKA = firstTbl.IDGKSTAVKA) <> IRA.IRAUKUPNO 
		
ORDER BY PARTNER.IDPARTNER, firstTbl.BROJDOKUMENTA
GO